/* Original project records are the single source for both lists and viewer. */
window.SAICases=[
{id:'024',name:'elevator',location:'오피스 복합공간 A · 2026',category:'업무 공간',title:'엘리베이터의 사회적 마찰 줄이기',image:'assets/elevator-cctv-reference.png',motion:'assets/elevator-cctv-reference.png',condition:'좁은 엘리베이터 안에서 두 사람이 함께 이동하는 상황.',behaviour:'두 사람이 서로를 의식하며 시선을 피하고, 침묵 속에서 위치를 조정합니다.',field:'고정된 위쪽 CCTV 하이앵글의 흑백 화면에서 두 사람 사이의 얇은 초록 흐름이 점차 감지되고 응집됩니다. 어색함이 커질수록 흐름이 모이는 표현입니다.',intervention:'승강 대기 위치와 내부 시선 방향을 분석하고, 층별 안내와 탑승 동선을 재설계했습니다.',result:'어색함 지수 31% 감소',metrics:[['기간','6주'],['참여자','142명'],['관찰 상황','684건'],['결과','31% 감소']]},
{id:'019',name:'going home',location:'서울 소재 대학 B · 2025',category:'교육 환경',title:'귀가 동선의 대화 단절 분석',image:'assets/field-campus-v2.webp',condition:'모임이 끝난 뒤 두 사람만 같은 방향으로 이동하는 상황.',behaviour:'함께 걷는 동안 대화가 끊기고 침묵이 이어집니다.',field:'대화가 멈추는 시점과 다시 시작할 수 있는 단서를 분석합니다. 이 사례의 A-Field 영상은 준비 중입니다.',intervention:'모임 이후 둘만 같은 방향으로 이동하는 상황을 분석하고 자연스러운 대화 재진입 단서를 제안했습니다.',result:'침묵 시간 24% 감소',metrics:[['기간','4주'],['참여자','86명'],['관찰 상황','312건'],['결과','24% 감소']]},
{id:'011',name:'narrow way',location:'복합문화공간 C · 2025',category:'서비스 공간',title:'좁은 통로의 동선 충돌 개선',image:'assets/field-service-v2.webp',condition:'좁은 통로에서 서로 반대 방향으로 이동하는 사람들이 마주치는 상황.',behaviour:'마주친 사람들이 이동 방향을 조정하며 동선이 겹칩니다.',field:'마주치는 지점의 폭과 시야, 안내 요소와 보행 방향을 분석합니다. 이 사례의 A-Field 영상은 준비 중입니다.',intervention:'사람이 마주치는 지점의 폭과 시야를 측정해 안내 요소와 보행 방향을 조정했습니다.',result:'경로 충돌 38% 감소',metrics:[['기간','8주'],['관찰','1,204건'],['개선안','7개'],['결과','38% 감소']]}
];
(() => {
const cases=window.SAICases, reduced=matchMedia('(prefers-reduced-motion: reduce)'), fine=matchMedia('(hover:hover) and (pointer:fine)');
const lists=[...document.querySelectorAll('[data-case-list]')];if(!lists.length)return;
// The archive list is a quiet text entry point; observation starts after selection.
lists.forEach(list=>list.querySelectorAll('[data-case]').forEach(button=>{const c=cases[Number(button.dataset.case)];button.classList.add('case-text-entry');button.textContent=`CASE ${c.id}: ${c.name.toUpperCase()}`;button.setAttribute('aria-label',`CASE ${c.id}: ${c.name.toUpperCase()} 사례 보기`);button.dataset.cursor='OPEN';}));
const dialog=document.createElement('dialog');dialog.className='case-dialog';dialog.id='case-viewer';dialog.setAttribute('aria-labelledby','case-title');
dialog.innerHTML=`<div class="case-toolbar"><span class="mono" data-case-code></span><button data-case-close aria-label="사례 뷰어 닫기">CLOSE ×</button></div><h2 class="case-title" id="case-title"></h2><div class="case-meta mono"><span data-case-location></span><span data-case-category></span><span>OBSERVATION ARCHIVE</span></div><button class="case-monitor" data-cursor="OBSERVE" aria-label="관측 이미지 확대" aria-pressed="false"><img alt=""/><span class="monitor-status mono"><span data-media-label></span><span class="extra">A-FIELD / VISUAL STUDY<br>CLICK TO EXPAND</span></span></button><div class="playback mono"><span data-media-caption></span><button data-toggle-cctv hidden>CCTV STUDY</button><button data-play aria-pressed="false"></button></div><div class="case-file"><div class="case-file-number" aria-hidden="true"></div><div data-file-body></div></div><div class="case-next"><button data-prev>← PREVIOUS CASE</button><button data-next>NEXT CASE →</button></div>`;
document.body.append(dialog);let current=0,opener=null,playing=false;
const image=dialog.querySelector('img'),monitor=dialog.querySelector('.case-monitor'),play=dialog.querySelector('[data-play]');
function render(index){current=index;const c=cases[index];playing=!reduced.matches;monitor.dataset.caseIndex=String(index);monitor.dataset.observation="true";dialog.querySelector('#case-title').textContent=c.name;dialog.querySelector('[data-case-code]').textContent=`CASE ${String(index+1).padStart(2,'0')} / 03 — RECORD ${c.id}`;dialog.querySelector('[data-case-location]').textContent=c.location;dialog.querySelector('[data-case-category]').textContent=c.category;image.src=playing?c.motion:c.image;image.alt=c.motion?'엘리베이터 안 두 사람과 초록 감지 흐름을 표현한 고정 하이앵글 흑백 모션 스터디':`${c.name}의 공간 맥락을 보여주는 참고 이미지`;monitor.classList.toggle('context',!c.motion);monitor.classList.remove('expanded');monitor.setAttribute('aria-pressed','false');monitor.setAttribute('aria-label','관측 이미지 확대');dialog.querySelector('[data-media-label]').textContent=c.motion?'CAM 01 / MOTION STUDY':'CONTEXT IMAGE / FOOTAGE PENDING';dialog.querySelector('.monitor-status .extra').innerHTML=c.motion?'A-FIELD / VISUAL STUDY<br>CLICK TO EXPAND':'CONTEXT REFERENCE<br>CLICK TO EXPAND';dialog.querySelector('[data-media-caption]').textContent='INTERACTIVE OBSERVATION / SIMULATED SIGNALS';play.hidden=false;dialog.querySelector("[data-toggle-cctv]").hidden=index!==0;setPlayLabel();dialog.querySelector('.case-file-number').textContent=String(index+1).padStart(2,'0');const body=dialog.querySelector('[data-file-body]');body.replaceChildren();[['CONDITION',c.condition],['OBSERVED BEHAVIOUR',c.behaviour],['A-FIELD RESPONSE',c.field],['INTERVENTION',c.intervention],['RESULT',c.result]].forEach(([label,copy])=>{const section=document.createElement('section');section.className='case-file-section';const h=document.createElement('h3');h.textContent=label;const p=document.createElement('p');p.textContent=copy;section.append(h,p);body.append(section)});const dl=document.createElement('dl');dl.className='case-metrics';c.metrics.forEach(([key,value])=>{const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;div.append(dt,dd);dl.append(div)});body.append(dl);dialog.querySelector('[data-prev]').disabled=index===0;dialog.querySelector('[data-next]').disabled=index===2;dialog.scrollTop=0;}
function setPlayLabel(){monitor.dataset.simPlaying=String(playing);monitor.dataset.fieldActive=String(current===0);monitor.dataset.fieldPlaying=String(playing);play.textContent=playing?'PAUSE':'PLAY';play.setAttribute('aria-pressed',String(playing));play.setAttribute('aria-label',playing?'시뮬레이션 일시정지':'시뮬레이션 재생')}
dialog.querySelector('[data-toggle-cctv]').addEventListener('click',()=>{const showing=monitor.dataset.observation==='true';monitor.dataset.observation=String(!showing);dialog.querySelector('[data-toggle-cctv]').textContent=showing?'BACK TO SIMULATION':'CCTV STUDY'});
function open(index,button,update=true){opener=button;render(index);if(!dialog.open)dialog.showModal();window.SAISignal?.pulse(dialog.querySelector('.case-title'),'slice');dialog.querySelector('[data-case-close]').focus({preventScroll:true});if(update){const url=new URL(location.href);url.hash=`project-${cases[index].id}`;history.replaceState(null,'',url)}}
function close(){dialog.close()}
lists.forEach(list=>list.querySelectorAll('[data-case]').forEach(button=>button.addEventListener('click',()=>open(Number(button.dataset.case),button))));
dialog.querySelector('[data-case-close]').addEventListener('click',close);dialog.addEventListener('close',()=>{image.removeAttribute('src');const url=new URL(location.href);if(/^#project-/.test(url.hash)){url.hash='';history.replaceState(null,'',url)}opener?.focus({preventScroll:true})});dialog.querySelector('[data-prev]').addEventListener('click',()=>open(current-1,opener));dialog.querySelector('[data-next]').addEventListener('click',()=>open(current+1,opener));play.addEventListener('click',()=>{playing=!playing;image.src=playing?cases[current].motion:cases[current].image;setPlayLabel()});monitor.addEventListener('click',()=>{const expanded=monitor.classList.toggle('expanded');monitor.setAttribute('aria-pressed',String(expanded));monitor.setAttribute('aria-label',expanded?'관측 이미지 축소':'관측 이미지 확대')});
function openHash(){const index=cases.findIndex(c=>location.hash===`#project-${c.id}`);if(index>=0)open(index,document.querySelector(`[data-case="${index}"]`),false)}openHash();window.addEventListener('hashchange',openHash);reduced.addEventListener('change',()=>{if(reduced.matches&&playing){playing=false;image.src=cases[current].image;setPlayLabel()}});
})();
