(() => {
const sheet=document.querySelector('.studio-sheet');if(!sheet)return;
const mobile=matchMedia('(max-width:700px)'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
const descriptions=['DISTANCE / INTERPERSONAL SPACING','GAZE / DIRECTION OF ATTENTION','MOTION / MOVEMENT THROUGH SPACE','DWELL / TIME SPENT IN PLACE','AVOIDANCE / PROXIMITY AND PATH'];
function diagram(mode,method=false){const green='var(--green)',gray='var(--muted)';const units='<g fill="var(--paper)"><circle cx="105" cy="114" r="9"/><path d="M94 130h22l5 34h-32zM96 164h7v25h-7zM108 164h7v25h-7z"/><circle cx="290" cy="114" r="9"/><path d="M279 130h22l5 34h-32zM281 164h7v25h-7zM293 164h7v25h-7z"/></g>';let marks='';if(method){if(mode===0)marks='<g fill="'+gray+'">'+[0,1,2,3,4,5].map(i=>`<circle cx="${155+i*17}" cy="${120+(i%2)*30}" r="2"/>`).join('')+'</g>';if(mode===1||mode===3)marks='<g fill="none" stroke="'+green+'" opacity=".6">'+[0,1,2,3,4].map(i=>`<path d="M125 ${128+i*5} Q205 ${mode===1?75+i*11:128+i*5} 272 ${128+i*5}"/>`).join('')+'</g>';if(mode===2)marks='<g stroke="'+gray+'" fill="none"><path d="M105 213h185m-185-5v10m185-10v10M123 139l149-20"/></g><text x="198" y="240" text-anchor="middle" fill="'+gray+'" font-size="9">DISTANCE / VECTOR</text>';}else{if(mode===0)marks='<path d="M105 213h185m-185-5v10m185-10v10" stroke="'+green+'" fill="none"/>';if(mode===1)marks='<path d="M114 113l158-35v72z" fill="'+green+'" opacity=".12"/><path d="M114 113l158-35m-158 35l158 37" stroke="'+green+'" opacity=".6"/>';if(mode===2)marks='<path d="M70 220Q180 240 326 202" stroke="'+green+'" fill="none" stroke-dasharray="5 7"/><path d="M316 200l10 2-6 8" stroke="'+green+'" fill="none"/>';if(mode===3)marks='<circle cx="105" cy="148" r="46" stroke="'+green+'" fill="none" stroke-dasharray="3 5"/><text x="170" y="220" fill="'+gray+'" font-size="9">DURATION / OBSERVATION</text>';if(mode===4)marks='<path d="M77 232Q190 198 166 142T302 62M302 232Q211 185 240 147T85 62" stroke="'+green+'" fill="none"/>';}
return '<svg viewBox="0 0 400 300" role="img" aria-label="'+(method?'Method':'Observation')+' concept diagram"><path d="M24 30H376V274H24Z" fill="none" stroke="var(--line)"/>'+units+marks+'<text x="24" y="18" fill="'+gray+'" font-family="Helvetica,Arial,sans-serif" font-size="9">SAI / CONCEPTUAL STUDY</text></svg>';}
const rows=[...sheet.querySelectorAll('[data-observation]')],preview=sheet.querySelector('.observation-preview'),index=sheet.querySelector('.observation-index');let current=-1;
function observe(i){current=i;rows.forEach((r,n)=>r.setAttribute('aria-expanded',String(n===i)));preview.querySelector('[data-observation-diagram]').innerHTML=diagram(i);preview.querySelector('[data-observation-caption]').textContent=descriptions[i];if(mobile.matches)rows[i].parentElement.append(preview);else index.append(preview);preview.classList.add('is-active');}
rows.forEach((row,i)=>{row.addEventListener('pointerenter',()=>{if(!mobile.matches)observe(i)});row.addEventListener('focus',()=>{if(!mobile.matches)observe(i)});row.addEventListener('click',()=>{if(current===i&&mobile.matches){preview.classList.remove('is-active');row.setAttribute('aria-expanded','false');current=-1}else observe(i)})});index.addEventListener('pointerleave',()=>{if(!mobile.matches){preview.classList.remove('is-active');rows.forEach(r=>r.setAttribute('aria-expanded','false'))}});mobile.addEventListener('change',()=>{if(current>=0)observe(current)});
const methods=[...sheet.querySelectorAll('[data-method]')],methodVisual=sheet.querySelector('[data-method-diagram]'),methodCaption=sheet.querySelector('[data-method-caption]'),labels=['TRACKING POINTS','A-FIELD DETECTION','DISTANCE / VECTOR','FIELD STABILIZATION'];function method(i){methods.forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));methodVisual.innerHTML=diagram(i,true);methodCaption.textContent=`0${i+1} / ${labels[i]}`;}methods.forEach((button,i)=>{button.addEventListener('pointerenter',()=>{if(!mobile.matches)method(i)});button.addEventListener('focus',()=>method(i));button.addEventListener('click',()=>method(i))});method(0);
// Keep the single existing explorer; summarize its original records without duplicating it.
const explorer=sheet.querySelector('.device-explorer'),records=JSON.parse(sheet.querySelector('#device-records').textContent),name=sheet.querySelector('[data-device-name]'),summary=document.createElement('dl');summary.className='sheet-metadata device-summary';name.parentElement.insertBefore(summary,sheet.querySelector('[data-device-signals]'));
function device(){const d=records.find(r=>r.model===name.textContent);if(!d)return;summary.replaceChildren();for(const [label,value]of [['MODEL',d.model],['TYPE',d.type],['INPUT',d.signals.join(' / ')],['STATUS',d.status]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);summary.append(row)}}device();new MutationObserver(device).observe(name,{childList:true});const inspect=sheet.querySelector('[data-open-inspection]');if(inspect)inspect.textContent='INSPECT DEVICE ↗';
// A restrained existing-artifact cue once the final statement has been read.
const final=sheet.querySelector('.statement-source');const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){if(!reduced.matches)window.SAISignal?.pulse(final,'slice');observer.disconnect()}},{threshold:1});observer.observe(final);
const archive=sheet.querySelector('.sheet-archive'),archivePreview=document.createElement('div');archivePreview.className='archive-preview';archivePreview.setAttribute('aria-hidden','true');archive.after(archivePreview);archive.querySelectorAll('tbody tr').forEach((row,i)=>{const show=()=>{if(mobile.matches)return;archivePreview.innerHTML=diagram([0,2,4][i]);archivePreview.classList.add('is-active')};row.addEventListener('pointerenter',show);row.addEventListener('focusin',show);row.addEventListener('pointerleave',()=>archivePreview.classList.remove('is-active'));row.addEventListener('focusout',()=>archivePreview.classList.remove('is-active'))});
})();
